// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzeexseyjejxmaifdktm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZWV4c2V5amVqeG1haWZka3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDQ2ODQsImV4cCI6MjA2ODAyMDY4NH0.qgqGYBRlJWfn91vEQa_mxDsE7mJSDoBM9OkziODnpFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});